services:
  frontend:
    image: php:8.2-apache                
    restart: always
    ports:
      - "8081:80"                        
    volumes:
      - ./frontend:/var/www/html
      - ./database/import_data:/var/www/html/data         
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    ports:
      - "5051:5000"  
    environment:
      - FLASK_ENV=development
      - APP_PORT=5000
      - ENCRYPT_SECRET_KEY=your_secret_key_here
      - DATABASE_URL=mysql+pymysql://backend_user:backend_password@database/petopia
    depends_on:
      database:
        condition: service_healthy

  db_migrations:
    image: flyway/flyway
    command: -url=jdbc:mysql://database?allowPublicKeyRetrieval=true -schemas=petopia -user=backend_user -password=backend_password -connectRetries=5 migrate
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./database/migrations:/flyway/sql

  import_data:
    build: ./database/import_data
    environment:
      - DB_CONNECTION_STRING=mysql+pymysql://backend_user:backend_password@database/petopia
    depends_on:
      - db_migrations

  database:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: petopia
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: backend_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  db_data:
